// example/index.svelte
<style>
:root {
  --svelte-color: #2563eb;
  --svelte-bg: #dbeafe;
  --asdf: 2px;
}

.panel {
  padding: 1rem;
  border-radius: 0.5rem;
  color: var(--svelte-color);
  background: var(--asdf);
  border-color: var(--asdf);
}
</style>

<div class="panel" style="border: 1px solid var(--svelte-color);">
  Svelte example
</div>

// example/index.vue
<template>
  <div
    class="container"
    style="color: var(--vue-color); background: var(--vue-bg)"
  >
    Vue example
  </div>
</template>

<style>
:root {
  --vue-color: #e11d48;
  --vue-bg: #ffe4e6;
}

.container {
  padding: 1rem;
  border: 1px solid var(--vue-color);
  color: var(--vue-bg);
}
</style>
